# Generated by Django 4.1.3 on 2022-11-18 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_rental',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='end_date',
        ),
        migrations.AddField(
            model_name='rental',
            name='movie_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Movies.movie'),
            preserve_default=False,
        ),
    ]
