# Generated by Django 4.1.3 on 2022-11-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_alter_rental_rental_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Movie_Rental',
        ),
    ]
