# Generated by Django 4.1.3 on 2022-11-22 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0007_rental_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Movie_Rental',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
